package src.oop.codes.oop_6.exceptionHandling;

public class try_catch {
    public static void main(String[] args) {

        // https://www.youtube.com/watch?v=1XAfapkBQjk&ab_channel=CodingwithJohn


        // so what this does is, when exception is found it catches it
        // does what we tell it to do and then continues the program ahead
        // note: it doesn't go back into the try but continues code
        // after try, if there is any....
        // if this try catch is not there, programs terminates
        // with exception error
//        for (int i = 2; i >= -2; i--) {
//
//            try {
//                System.out.println(10 / i);
//            } catch (Exception e) {
//                System.out.println(e.getMessage());
//            }
            /*
   finally {
         // every time it goes inside try, the program
         // always executes finally, whether exception is found or not
        System.out.println("done");
    }
             */
//           }
    }
}
